# fly.toml app configuration file for employee-management-api

app = 'employee-management-api'
primary_region = 'sin'

[build]
  dockerfile = "./Dockerfile"

[deploy]
  strategy = "immediate"
  min_machines_running = 1

[env]
  MONGODB_URI = "mongodb://127.0.0.1:27017/employee-db"
  PORT = "4000"

[experimental]
  cmd = ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

[[services]]
  internal_port = 4000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "2s"

[[services]]
  internal_port = 27017
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["tls"]
    port = 27017

[[mounts]]
  source = "mongodb_data"
  destination = "/data/db"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024